/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 * 
 * @author tomia
 */

public class RegistrationUI extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationUI
     */
    public RegistrationUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        passErrorLabel = new javax.swing.JLabel();
        userErrorLabel = new javax.swing.JLabel();
        displayErrorLabel = new javax.swing.JLabel();
        emptyErrorLabel = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        displayNameLabel = new javax.swing.JLabel();
        zipLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        displayNameField = new javax.swing.JTextField();
        zipCodeField = new javax.swing.JTextField();
        confirmationButton = new javax.swing.JButton();
        confirmPassLabel = new javax.swing.JLabel();
        confirmPassField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("Create an Account");

        passErrorLabel.setForeground(new java.awt.Color(144, 0, 0));
        passErrorLabel.setText("ERROR: Password does not match");

        userErrorLabel.setForeground(new java.awt.Color(144, 0, 0));
        userErrorLabel.setText("ERROR: Username already exists.");

        displayErrorLabel.setForeground(new java.awt.Color(144, 0, 0));
        displayErrorLabel.setText("ERROR: Display Name already exists.");

        emptyErrorLabel.setForeground(new java.awt.Color(144, 0, 0));
        emptyErrorLabel.setText("ERROR: You must fill in all fields");

        doneButton.setText("Done");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emptyErrorLabel)
                            .addComponent(displayErrorLabel)
                            .addComponent(userErrorLabel)
                            .addComponent(passErrorLabel)
                            .addComponent(titleLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(doneButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(emptyErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doneButton)
                .addContainerGap())
        );

        userLabel.setText("Username:");

        passLabel.setText("Password:");

        displayNameLabel.setText("Display Name:");

        zipLabel.setText("Zipcode:");

        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });

        confirmationButton.setText("Confirm");
        confirmationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmationButtonActionPerformed(evt);
            }
        });

        confirmPassLabel.setText("Confirm Password:");

        confirmPassField.setMinimumSize(new java.awt.Dimension(107, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passLabel)
                            .addComponent(userLabel))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmPassLabel)
                            .addComponent(displayNameLabel)
                            .addComponent(zipLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmationButton))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPassLabel)
                    .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmationButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmationButtonActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmPassField;
    private javax.swing.JLabel confirmPassLabel;
    public javax.swing.JButton confirmationButton;
    private javax.swing.JLabel displayErrorLabel;
    private javax.swing.JTextField displayNameField;
    private javax.swing.JLabel displayNameLabel;
    public javax.swing.JButton doneButton;
    private javax.swing.JLabel emptyErrorLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passErrorLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userErrorLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userNameField;
    private javax.swing.JTextField zipCodeField;
    private javax.swing.JLabel zipLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the confirmPassField
     */
    public javax.swing.JTextField getConfirmPassField() {
        return confirmPassField;
    }

    /**
     * @param confirmPassField the confirmPassField to set
     */
    public void setConfirmPassField(javax.swing.JTextField confirmPassField) {
        this.confirmPassField = confirmPassField;
    }

    /**
     * @return the confirmPassLabel
     */
    public javax.swing.JLabel getConfirmPassLabel() {
        return confirmPassLabel;
    }

    /**
     * @param confirmPassLabel the confirmPassLabel to set
     */
    public void setConfirmPassLabel(javax.swing.JLabel confirmPassLabel) {
        this.confirmPassLabel = confirmPassLabel;
    }

    /**
     * @return the displayNameField
     */
    public javax.swing.JTextField getDisplayNameField() {
        return displayNameField;
    }

    /**
     * @param displayNameField the displayNameField to set
     */
    public void setDisplayNameField(javax.swing.JTextField displayNameField) {
        this.displayNameField = displayNameField;
    }

    /**
     * @return the displayNameLabel
     */
    public javax.swing.JLabel getDisplayNameLabel() {
        return displayNameLabel;
    }

    /**
     * @param displayNameLabel the displayNameLabel to set
     */
    public void setDisplayNameLabel(javax.swing.JLabel displayNameLabel) {
        this.displayNameLabel = displayNameLabel;
    }

    /**
     * @return the errorLabel2
     */
    public javax.swing.JLabel getPassErrorLabel() {
        return passErrorLabel;
    }

    /**
     * @param passErrorLabel the passErrorLabel to set
     */
    public void setPassErrorLabel(javax.swing.JLabel passErrorLabel) {
        this.passErrorLabel = passErrorLabel;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the passLabel
     */
    public javax.swing.JLabel getPassLabel() {
        return passLabel;
    }

    /**
     * @param passLabel the passLabel to set
     */
    public void setPassLabel(javax.swing.JLabel passLabel) {
        this.passLabel = passLabel;
    }

    /**
     * @return the passwordField
     */
    public javax.swing.JTextField getPasswordField() {
        return passwordField;
    }

    /**
     * @param passwordField the passwordField to set
     */
    public void setPasswordField(javax.swing.JTextField passwordField) {
        this.passwordField = passwordField;
    }

    /**
     * @return the titleLabel
     */
    public javax.swing.JLabel getTitleLabel() {
        return titleLabel;
    }

    /**
     * @param titleLabel the titleLabel to set
     */
    public void setTitleLabel(javax.swing.JLabel titleLabel) {
        this.titleLabel = titleLabel;
    }

    /**
     * @return the userLabel
     */
    public javax.swing.JLabel getUserLabel() {
        return userLabel;
    }

    /**
     * @param userLabel the userLabel to set
     */
    public void setUserLabel(javax.swing.JLabel userLabel) {
        this.userLabel = userLabel;
    }

    /**
     * @return the userNameField
     */
    public javax.swing.JTextField getUserNameField() {
        return userNameField;
    }

    /**
     * @param userNameField the userNameField to set
     */
    public void setUserNameField(javax.swing.JTextField userNameField) {
        this.userNameField = userNameField;
    }

    /**
     * @return the zipCodeField
     */
    public javax.swing.JTextField getZipCodeField() {
        return zipCodeField;
    }

    /**
     * @param zipCodeField the zipCodeField to set
     */
    public void setZipCodeField(javax.swing.JTextField zipCodeField) {
        this.zipCodeField = zipCodeField;
    }

    /**
     * @return the zipLabel
     */
    public javax.swing.JLabel getZipLabel() {
        return zipLabel;
    }

    /**
     * @param zipLabel the zipLabel to set
     */
    public void setZipLabel(javax.swing.JLabel zipLabel) {
        this.zipLabel = zipLabel;
    }

    public javax.swing.JLabel getDisplayErrorLabel() {
        return displayErrorLabel;
    }

    public void setDisplayErrorLabel(javax.swing.JLabel displayErrorLabel) {
        this.displayErrorLabel = displayErrorLabel;
    }

    public javax.swing.JLabel getEmptyErrorLabel() {
        return emptyErrorLabel;
    }

    public void setEmptyErrorLabel(javax.swing.JLabel emptyErrorLabel) {
        this.emptyErrorLabel = emptyErrorLabel;
    }

    public javax.swing.JLabel getUserErrorLabel() {
        return userErrorLabel;
    }

    public void setUserErrorLabel(javax.swing.JLabel userErrorLabel) {
        this.userErrorLabel = userErrorLabel;
    }
}
